name: mahmoud_widgets
description: some of widgets
version: 1.0.7
homepage: https://github.com/mazab99/mahmoud_widgets

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
